### ISSUE TITLE
CC01 - Wifi

### ISSUE THREAD

**Issue by tresor-ndeng** [gti525/h18-mobile-scan#5]
En tant qu'application de scanneur, je dois rechercher le réseau WIFI "GTI525" et m’y connecter si possible. Si le réseau n’est pas disponible, je dois afficher le message “Réseau introuvable”. Si le réseau est disponible, mais l’API ne répond pas, je dois afficher le message “Serveur indisponible”

**Comment by nicolas-habak** [comment]
En tant qu'application de scanneur, je dois rechercher le réseau WIFI "GTI525" et m’y connecter si possible. Si le réseau n’est pas disponible, je dois afficher le message “Réseau introuvable”. Si le réseau est disponible, mais l’API ne répond pas, je dois afficher le message “Serveur indisponible”

**Comment by nicolas-habak** [comment]
Bouton reconnexion, automatiquement première page (invisible)
